INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Charmander', 'Fire lizard Pokémon.', 'Ember', '30', 'Water', '', '1', 4, 1, 1),
(50, 'Squirtle', 'Tiny turtle Pokémon.', 'Bubble', '20', 'Electric', '', '1', 7, 2, 1),
(45, 'Bulbasaur', 'Seed Pokémon.', 'Vine Whip', '20', 'Fire', '', '1', 3, 3, 1),
(70, 'Pikachu', 'Mouse Pokémon with shocking speed.', 'Thunderbolt', '40', 'Ground', '', '1', 12, 4, 1),
(60, 'Gastly', 'Gaseous ghost Pokémon.', 'Lick', '10', 'Psychic', 'Normal', '0', 24, 5, 1),
(80, 'Charmeleon', 'Evolved form of Charmander.', 'Flamethrower', '50', 'Water', '', '2', 5, 1, 2),
(70, 'Wartortle', 'Evolves from Squirtle.', 'Aqua Tail', '40', 'Grass', '', '2', 5, 2, 2),
(60, 'Ivysaur', 'Evolves from Bulbasaur.', 'Razor Leaf', '30', 'Fire', '', '2', 5, 3, 2),
(90, 'Raichu', 'Evolved Pikachu.', 'Thunder Punch', '50', 'Fighting', '', '1', 5, 4, 2),
(55, 'Haunter', 'Gas ghost Pokémon.', 'Nightmare', '30', 'Psychic', '', '0', 5, 5, 2),
(100, 'Charizard', 'Dragon-like flame Pokémon.', 'Fire Spin', '100', 'Water', 'Grass', '3', 6, 1, 3),
(90, 'Blastoise', 'Giant turtle cannon Pokémon.', 'Hydro Pump', '60', 'Electric', '', '3', 6, 2, 3),
(85, 'Venusaur', 'Huge floral Pokémon.', 'Solar Beam', '80', 'Fire', '', '3', 6, 3, 3),
(110, 'Alakazam', 'Psychic power Pokémon.', 'Psybeam', '60', 'Dark', '', '2', 6, 5, 3),
(40, 'Magnemite', 'Steel electric Pokémon.', 'Spark', '20', 'Fighting', 'Steel', '1', 15, 4, 1),
(50, 'Jigglypuff', 'Balloon Pokémon.', 'Sing', '0', 'Steel', '', '1', 17, 5, 1),
(60, 'Eevee', 'Evolution Pokémon.', 'Tackle', '10', 'Fighting', '', '1', 18, 3, 1),
(55, 'Meowth', 'Scratch cat Pokémon.', 'Fury Swipes', '20', 'Fighting', '', '1', 18, 4, 1),
(70, 'Growlithe', 'Puppy Pokémon.', 'Flame Tail', '30', 'Water', '', '1', 18, 1, 1),
(90, 'Gengar', 'Evolved from Haunter.', 'Shadow Ball', '70', 'Dark', '', '1', 18, 5, 3);