INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(50, 'Oddish', 'Weed Pokémon that grows in the moonlight.', 'Absorb', '10', 'Fire', '', '1', 12, 3, 1),
(60, 'Poliwag', 'Tadpole Pokémon with a swirl on its belly.', 'Bubble', '10', 'Electric', '', '1', 12, 2, 1),
(70, 'Machop', 'Strong arm Pokémon.', 'Karate Chop', '20', 'Psychic', '', '1', 12, 5, 1),
(50, 'Magnemite', 'Magnetic electric Pokémon.', 'Shock Wave', '20', 'Fighting', 'Steel', '1', 12, 4, 1),
(60, 'Sandshrew', 'Mouse that lives in the desert.', 'Slash', '30', 'Water', '', '1', 12, 4, 1),
(80, 'Pidgeotto', 'Bird Pokémon evolved from Pidgey.', 'Gust', '30', 'Electric', '', '1', 13, 3, 2),
(55, 'Nidorino', 'Evolves from Nidoran♂.', 'Horn Attack', '40', 'Psychic', '', '1', 13, 3, 2),
(40, 'Abra', 'Psi Pokémon with teleportation powers.', 'Teleport', '0', 'Psychic', '', '1', 13, 5, 1),
(100, 'Onix', 'Rock snake Pokémon.', 'Rock Throw', '50', 'Grass', '', '3', 13, 4, 1),
(80, 'Arbok', 'Evolves from Ekans, intimidating glare.', 'Poison Fang', '40', 'Psychic', '', '2', 13, 3, 2),
(60, 'Slowpoke', 'Always seems dazed.', 'Tackle', '10', 'Electric', '', '2', 13, 2, 1),
(90, 'Fearow', 'Evolved bird Pokémon.', 'Drill Peck', '60', 'Electric', '', '1', 13, 3, 2),
(70, 'Electrode', 'Ball Pokémon that stores electricity.', 'Thunder Shock', '40', 'Ground', 'Steel', '2', 13, 4, 2),
(65, 'Koffing', 'Smoggy floating Pokémon.', 'Smokescreen', '20', 'Psychic', '', '1', 13, 5, 1),
(80, 'Dodrio', 'Three-headed bird Pokémon.', 'Tri Attack', '60', 'Electric', '', '1', 13, 3, 2),
(75, 'Lickitung', 'Uses its tongue to confuse foes.', 'Lick', '10', 'Fighting', '', '1', 13, 5, 1),
(95, 'Hitmonlee', 'Kicking master Pokémon.', 'Jump Kick', '50', 'Psychic', '', '1', 13, 5, 2),
(60, 'Seel', 'Chilling water Pokémon.', 'Headbutt', '20', 'Electric', '', '1', 14, 2, 1),
(50, 'Krabby', 'Crab Pokémon with strong claws.', 'Crabhammer', '30', 'Electric', '', '1', 14, 2, 1),
(40, 'Voltorb', 'Electric ball Pokémon.', 'Charge', '10', 'Fighting', '', '1', 14, 4, 1),
(70, 'Shellder', 'Clam Pokémon with a hard shell.', 'Clamp', '30', 'Electric', '', '1', 14, 2, 1),
(90, 'Cloyster', 'Evolves from Shellder.', 'Aurora Beam', '40', 'Electric', '', '2', 14, 2, 2),
(100, 'Kingler', 'Evolves from Krabby with powerful claws.', 'Crabhammer', '50', 'Electric', '', '2', 14, 2, 2),
(80, 'Dewgong', 'Evolves from Seel.', 'Ice Beam', '40', 'Electric', '', '2', 14, 2, 2),
(85, 'Electabuzz', 'Electric fighter Pokémon.', 'Thunder Punch', '60', 'Ground', '', '2', 14, 4, 2),
(70, 'Jynx', 'Ice psychic Pokémon.', 'Lovely Kiss', '30', 'Dark', '', '1', 14, 5, 2),
(55, 'Horsea', 'Dragon-like water Pokémon.', 'Bubble', '20', 'Electric', '', '1', 14, 2, 1),
(65, 'Goldeen', 'Elegant water Pokémon.', 'Horn Attack', '30', 'Electric', '', '1', 14, 2, 1),
(90, 'Seadra', 'Evolves from Horsea.', 'Water Gun', '40', 'Electric', '', '2', 14, 2, 2),
(95, 'Starmie', 'Evolves from Staryu with psychic powers.', 'Recover', '0', 'Dark', '', '1', 14, 5, 2);