INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(60, 'Pidgey', 'Tiny bird Pokémon.', 'Gust', '20', 'Electric', '', '1', 15, 3, 1),
(70, 'Nidoran♀', 'Poison pin Pokémon.', 'Scratch', '10', 'Psychic', '', '1', 15, 3, 1),
(65, 'Nidoran♂', 'Spiky ear Pokémon.', 'Peck', '20', 'Psychic', '', '1', 15, 3, 1),
(80, 'Persian', 'Evolved from Meowth.', 'Slash', '40', 'Fighting', '', '1', 15, 4, 2),
(60, 'Vulpix', 'Fox Pokémon with fiery tail.', 'Flame', '20', 'Water', '', '1', 15, 1, 1),
(90, 'Ninetales', 'Evolves from Vulpix.', 'Fire Blast', '80', 'Water', '', '2', 15, 1, 2),
(70, 'Growlithe', 'Flame pup Pokémon.', 'Bite', '30', 'Water', '', '1', 15, 1, 1),
(100, 'Arcanine', 'Evolved legendary pup.', 'Extreme Speed', '90', 'Water', '', '3', 15, 1, 2),
(55, 'Tentacool', 'Jellyfish Pokémon.', 'Acid', '20', 'Psychic', '', '1', 15, 2, 1),
(85, 'Tentacruel', 'Evolved jellyfish Pokémon.', 'Poison Sting', '50', 'Psychic', '', '2', 15, 2, 2),
(65, 'Geodude', 'Rocky boulder Pokémon.', 'Rock Throw', '30', 'Grass', '', '1', 15, 4, 1),
(90, 'Graveler', 'Evolves from Geodude.', 'Magnitude', '50', 'Grass', '', '2', 15, 4, 2),
(110, 'Golem', 'Final form of Geodude.', 'Earthquake', '80', 'Grass', '', '3', 15, 4, 3),
(60, 'Mankey', 'Wild monkey Pokémon.', 'Low Kick', '20', 'Psychic', '', '1', 15, 5, 1),
(85, 'Primeape', 'Furious fighter Pokémon.', 'Karate Chop', '60', 'Psychic', '', '2', 15, 5, 2),
(100, 'Hitmonchan', 'Boxing Pokémon.', 'Mach Punch', '70', 'Psychic', '', '1', 15, 5, 2),
(55, 'Psyduck', 'Duck with constant headache.', 'Scratch', '10', 'Electric', '', '1', 16, 2, 1),
(75, 'Golduck', 'Evolves from Psyduck.', 'Water Pulse', '50', 'Electric', '', '2', 16, 2, 2),
(70, 'Slowbro', 'Shellder-bitten tail Pokémon.', 'Psychic', '60', 'Dark', '', '2', 16, 5, 2),
(60, 'Shelgon', 'Armored dragon Pokémon.', 'Protect', '0', 'Fairy', '', '1', 16, 3, 2),
(110, 'Salamence', 'Mighty dragon Pokémon.', 'Dragon Claw', '90', 'Ice', '', '3', 16, 3, 3),
(85, 'Snorlax', 'Sleepy but strong.', 'Body Slam', '70', 'Fighting', '', '4', 16, 5, 1),
(40, 'Diglett', 'Mole Pokémon.', 'Dig', '20', 'Grass', '', '1', 16, 4, 1),
(70, 'Dugtrio', 'Three-headed Diglett evolution.', 'Earthquake', '60', 'Grass', '', '2', 16, 4, 2),
(50, 'Zubat', 'Bat Pokémon that lives in caves.', 'Leech Life', '20', 'Electric', '', '1', 16, 5, 1),
(80, 'Golbat', 'Evolves from Zubat.', 'Wing Attack', '40', 'Electric', '', '2', 16, 5, 2),
(100, 'Crobat', 'Final evolution of Zubat.', 'Poison Fang', '70', 'Psychic', '', '3', 16, 5, 3),
(75, 'Togepi', 'Tiny egg Pokémon.', 'Charm', '0', 'Steel', '', '1', 16, 3, 1),
(85, 'Togetic', 'Evolves from Togepi.', 'Metronome', '50', 'Steel', '', '2', 16, 3, 2),
(105, 'Togekiss', 'Final form, flying serene Pokémon.', 'Air Slash', '80', 'Steel', '', '3', 16, 3, 3);